field: ea96aca2-ea64-4585-b084-6cfd680271e1 # Home Buckets
fieldLayouts:
  e1e3be47-29dc-469f-ba3d-1e2fa7fd8789:
    tabs:
      -
        fields:
          188eaaca-c881-4c3f-96e3-f0a8fec28636: # Link URL
            required: true
            sortOrder: 5
          3738bc09-42b3-421c-8dce-fad8a340f8e8: # Headline
            required: true
            sortOrder: 2
          50697409-d605-4863-b4ac-bb97c5881924: # Link Text
            required: true
            sortOrder: 4
          bb004981-81b9-4612-824b-5d7781e3ed3f: # Image
            required: true
            sortOrder: 1
          f26d2c7f-68be-4794-ad59-7d0d35b3fad5: # Excerpt
            required: true
            sortOrder: 3
        name: Content
        sortOrder: 1
fields:
  188eaaca-c881-4c3f-96e3-f0a8fec28636: # Link URL
    contentColumnType: text
    fieldGroup: null
    handle: linkUrl
    instructions: ''
    name: 'Link URL'
    searchable: true
    settings:
      charLimit: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  3738bc09-42b3-421c-8dce-fad8a340f8e8: # Headline
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      charLimit: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  50697409-d605-4863-b4ac-bb97c5881924: # Link Text
    contentColumnType: text
    fieldGroup: null
    handle: linkText
    instructions: ''
    name: 'Link Text'
    searchable: true
    settings:
      charLimit: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  bb004981-81b9-4612-824b-5d7781e3ed3f: # Image
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: 'Add an Image'
      singleUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      singleUploadLocationSubpath: ''
      sources: '*'
      useSingleFolder: '1'
      viewMode: list
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Assets
  f26d2c7f-68be-4794-ad59-7d0d35b3fad5: # Excerpt
    contentColumnType: string
    fieldGroup: null
    handle: excerpt
    instructions: ''
    name: Excerpt
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: '1'
      columnType: text
      configFile: ''
      purifyHtml: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: bucket
name: Bucket
sortOrder: 1
