field: 28b935de-0139-4bde-bdbd-1323a9f2f676 # Home Courses
fieldLayouts:
  6f6a5713-db99-45ff-8822-8c5604295e40:
    tabs:
      -
        fields:
          9ac36cd6-f8a3-4875-947e-fe3347369e24: # Headline
            required: false
            sortOrder: 2
          47d754b9-1700-4868-8979-47032cb893cd: # Image
            required: false
            sortOrder: 1
          76ea3674-0bc3-44f7-9744-26866d2c7eec: # Link
            required: false
            sortOrder: 5
          713a4f89-9d22-4ac3-b163-200d025dcb9e: # Phone
            required: false
            sortOrder: 3
          f9251f64-af2b-45d5-a9bf-b3cbad6bb6f1: # Address
            required: false
            sortOrder: 4
        name: Content
        sortOrder: 1
fields:
  9ac36cd6-f8a3-4875-947e-fe3347369e24: # Headline
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      charLimit: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  47d754b9-1700-4868-8979-47032cb893cd: # Image
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: ''
      singleUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      singleUploadLocationSubpath: ''
      sources: '*'
      useSingleFolder: ''
      viewMode: list
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Assets
  76ea3674-0bc3-44f7-9744-26866d2c7eec: # Link
    contentColumnType: string
    fieldGroup: null
    handle: linkData
    instructions: ''
    name: Link
    searchable: true
    settings:
      allowCustomText: '1'
      allowTarget: '1'
      assetSelectionLabel: 'Select an asset'
      assetSources: '*'
      categorySelectionLabel: 'Select a category'
      categorySources: '*'
      defaultText: ''
      entrySelectionLabel: 'Select an entry'
      entrySources: '*'
      types:
        - custom
        - entry
    translationKeyFormat: null
    translationMethod: none
    type: FruitLinkIt
  713a4f89-9d22-4ac3-b163-200d025dcb9e: # Phone
    contentColumnType: text
    fieldGroup: null
    handle: phone
    instructions: ''
    name: Phone
    searchable: true
    settings:
      charLimit: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f9251f64-af2b-45d5-a9bf-b3cbad6bb6f1: # Address
    contentColumnType: text
    fieldGroup: null
    handle: address
    instructions: ''
    name: Address
    searchable: true
    settings:
      charLimit: ''
      columnType: text
      initialRows: '3'
      multiline: '1'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: course
name: Course
sortOrder: 1
