field: f3bf264b-71a5-4af8-9f9d-f2830e9cf33f # Dining Options
fieldLayouts:
  dc43201d-a83c-44e7-8241-38cd73a7bb0d:
    tabs:
      -
        fields:
          3bc66f93-926c-4e23-a173-a807a5e9b3be: # Headline
            required: true
            sortOrder: 1
          37f54e62-0b62-426a-8d3a-d2890b714689: # Menus
            required: false
            sortOrder: 4
          92f15527-4946-402a-b282-530cd0000b1e: # Details List
            required: false
            sortOrder: 3
          412a248c-6877-45ce-a772-65fb0c295ac3: # Gallery
            required: false
            sortOrder: 5
          ad6faca2-5d60-4a28-866e-e60da73626d0: # Description
            required: false
            sortOrder: 2
        name: Content
        sortOrder: 1
fields:
  3bc66f93-926c-4e23-a173-a807a5e9b3be: # Headline
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      charLimit: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  37f54e62-0b62-426a-8d3a-d2890b714689: # Menus
    contentColumnType: string
    fieldGroup: null
    handle: menus
    instructions: ''
    name: Menus
    searchable: 1
    settings:
      columns:
        176:
          width: ''
        177:
          width: ''
      fieldLayout: row
      maxRows: null
      minRows: null
      propagationMethod: all
      selectionLabel: 'Add a Menu'
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
  92f15527-4946-402a-b282-530cd0000b1e: # Details List
    contentColumnType: text
    fieldGroup: null
    handle: detailsList
    instructions: ''
    name: 'Details List'
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - handle
                  - label
                -
                  - heading
                  - Label
                -
                  - type
                  - singleline
                -
                  - width
                  - ''
          -
            - col2
            -
              __assoc__:
                -
                  - handle
                  - detail
                -
                  - heading
                  - Detail
                -
                  - type
                  - singleline
                -
                  - width
                  - ''
      defaults:
        __assoc__:
          -
            - row1
            -
              __assoc__:
                -
                  - col1
                  - ''
                -
                  - col2
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  412a248c-6877-45ce-a772-65fb0c295ac3: # Gallery
    contentColumnType: string
    fieldGroup: null
    handle: gallery
    instructions: ''
    name: Gallery
    searchable: true
    settings:
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: 'Add an image'
      singleUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
      singleUploadLocationSubpath: ''
      sources: '*'
      useSingleFolder: '1'
      viewMode: list
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Assets
  ad6faca2-5d60-4a28-866e-e60da73626d0: # Description
    contentColumnType: string
    fieldGroup: null
    handle: description
    instructions: ''
    name: Description
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: '1'
      columnType: text
      configFile: ''
      purifyHtml: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: diningOption
name: 'Dining Option'
sortOrder: 1
