field: a2e1e7c1-d07f-4b31-b03a-d0851e8d2833 # Rates Overview
fieldLayouts:
  81a531a7-99ac-44d9-9b21-e8b1a73e4e4d:
    tabs:
      -
        fields:
          00a79945-0f76-4aac-a30c-9d1f11441a84: # Table Footer
            required: false
            sortOrder: 3
          0fa1c15b-4316-4ff5-8918-6e3511d816d1: # Items to Note
            required: false
            sortOrder: 4
          5c1f657e-0879-4a4b-beca-79003bf50cce: # Table
            required: false
            sortOrder: 2
          42076b35-8ab3-43d2-8ae3-980b5c280b2c: # Headline
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  00a79945-0f76-4aac-a30c-9d1f11441a84: # Table Footer
    contentColumnType: text
    fieldGroup: null
    handle: tableFooter
    instructions: ''
    name: 'Table Footer'
    searchable: true
    settings:
      charLimit: ''
      columnType: text
      initialRows: '4'
      multiline: '1'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  0fa1c15b-4316-4ff5-8918-6e3511d816d1: # Items to Note
    contentColumnType: string
    fieldGroup: null
    handle: itemsToNote
    instructions: ''
    name: 'Items to Note'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: '1'
      columnType: text
      configFile: ''
      purifyHtml: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  5c1f657e-0879-4a4b-beca-79003bf50cce: # Table
    contentColumnType: text
    fieldGroup: null
    handle: table
    instructions: ''
    name: Table
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - handle
                  - dates
                -
                  - heading
                  - Dates
                -
                  - type
                  - singleline
                -
                  - width
                  - ''
          -
            - col2
            -
              __assoc__:
                -
                  - handle
                  - standard
                -
                  - heading
                  - Standard
                -
                  - type
                  - singleline
                -
                  - width
                  - ''
          -
            - col3
            -
              __assoc__:
                -
                  - handle
                  - twilight
                -
                  - heading
                  - Twilight
                -
                  - type
                  - singleline
                -
                  - width
                  - ''
          -
            - col4
            -
              __assoc__:
                -
                  - handle
                  - replay
                -
                  - heading
                  - Replay
                -
                  - type
                  - singleline
                -
                  - width
                  - ''
      defaults:
        __assoc__:
          -
            - row1
            -
              __assoc__:
                -
                  - col1
                  - ''
                -
                  - col2
                  - ''
                -
                  - col3
                  - ''
                -
                  - col4
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  42076b35-8ab3-43d2-8ae3-980b5c280b2c: # Headline
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      charLimit: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: ratesTable
name: 'Rates Table'
sortOrder: 1
