fieldLayouts:
  02fd76cf-07f3-4227-adf6-d4be3eb471fe:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 9baae7f8-cf5b-40da-96a9-1a49f83765dd # Related Entry
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 0f2543ba-0c6c-4a11-8c70-9cdefad272dc # Custom URL
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Menu
        sortOrder: 1
handle: footerMenu
hasTitleField: true
name: 'Footer Menu'
section: 9e6b2974-b890-456f-9a6f-75fef8b49e24 # Footer Menu
sortOrder: 1
titleFormat: null
