fieldLayouts:
  65e32591-f79f-4ad1-adfe-0193ccb9df88:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 9baae7f8-cf5b-40da-96a9-1a49f83765dd # Related Entry
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 0f2543ba-0c6c-4a11-8c70-9cdefad272dc # Custom URL
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Menu
        sortOrder: 1
handle: mobileMenu
hasTitleField: true
name: 'Mobile Menu'
section: 2b8ba9ac-0e3e-470d-9eb1-905e54cb0a6f # Mobile Menu
sortOrder: 1
titleFormat: null
