fieldLayouts:
  c304ec06-16b5-40cc-a3cd-67799e085c79:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 9baae7f8-cf5b-40da-96a9-1a49f83765dd # Related Entry
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 0f2543ba-0c6c-4a11-8c70-9cdefad272dc # Custom URL
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Menu
        sortOrder: 1
handle: secondaryMenu
hasTitleField: true
name: 'Secondary Menu'
section: 0658bece-cc90-460f-bedc-b298ebf8037b # Secondary Menu
sortOrder: 1
titleFormat: null
