contentColumnType: string
fieldGroup: 267e048a-991b-4411-a5f9-82512829882d # Home
handle: homeIntro
instructions: ''
name: 'Home Intro'
searchable: true
settings:
  contentTable: '{{%matrixcontent_homeintro}}'
  maxBlocks: '1'
  propagationMethod: all
translationKeyFormat: null
translationMethod: none
type: craft\fields\Matrix
