contentColumnType: string
fieldGroup: 267e048a-991b-4411-a5f9-82512829882d # Home
handle: homeFooterImage
instructions: ''
name: 'Home Footer Image'
searchable: true
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: 'Add an Image'
  singleUploadLocationSource: 'volume:0c261a33-5269-4599-9373-5f2b4037a4a1' # General
  singleUploadLocationSubpath: ''
  sources: '*'
  useSingleFolder: '1'
  viewMode: large
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
