contentColumnType: text
fieldGroup: 267e048a-991b-4411-a5f9-82512829882d # Home
handle: homeCoursesHeadline
instructions: ''
name: 'Home Courses Headline'
searchable: true
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
