contentColumnType: string
fieldGroup: 267e048a-991b-4411-a5f9-82512829882d # Home
handle: homeSlider
instructions: ''
name: 'Home Slider'
searchable: true
settings:
  contentTable: '{{%matrixcontent_homeslider}}'
  maxBlocks: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: none
type: craft\fields\Matrix
