contentColumnType: string
fieldGroup: 27878486-148f-45b2-8d48-2a355ca5370b # Globals
handle: instagram
instructions: ''
name: Instagram
searchable: true
settings:
  followRedirects: ''
translationKeyFormat: null
translationMethod: none
type: VzUrl
