contentColumnType: string
fieldGroup: f166e127-51d5-4ea5-9f69-0e3973d61913 # Rates
handle: itemsToKnow
instructions: ''
name: 'Items to Know'
searchable: 1
settings:
  columns:
    new1:
      width: ''
    new2:
      width: ''
  fieldLayout: row
  maxRows: null
  minRows: null
  propagationMethod: all
  selectionLabel: 'Add a row'
  staticField: '1'
translationKeyFormat: null
translationMethod: none
type: verbb\supertable\fields\SuperTableField
