contentColumnType: string
fieldGroup: f166e127-51d5-4ea5-9f69-0e3973d61913 # Rates
handle: ratesOverview
instructions: ''
name: 'Rates Overview'
searchable: true
settings:
  contentTable: '{{%matrixcontent_ratesoverview}}'
  maxBlocks: '1'
  propagationMethod: all
translationKeyFormat: null
translationMethod: none
type: craft\fields\Matrix
