contentColumnType: string
fieldGroup: 441642ef-65bb-460b-bf11-9a7b5014942b # Contact
handle: staffContacts
instructions: ''
name: 'Staff Contacts'
searchable: true
settings:
  contentTable: '{{%matrixcontent_staffcontacts}}'
  maxBlocks: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: none
type: craft\fields\Matrix
