contentColumnType: string
fieldGroup: 2de0d27e-44cc-4a0b-b5b3-4e9537340946 # Default
handle: video
instructions: ''
name: Video
searchable: true
settings:
  contentTable: '{{%matrixcontent_video}}'
  maxBlocks: '1'
  propagationMethod: all
translationKeyFormat: null
translationMethod: none
type: craft\fields\Matrix
