fieldLayouts:
  ce5cb46d-484f-4e62-ae1d-46a695609422:
    tabs:
      -
        fields:
          0ce3edeb-61cd-41d6-9105-8c1d6c8d3be1: # Staging Snippet
            required: false
            sortOrder: 2
          ad185f5b-815b-4a9e-8e04-99cc8b28b78d: # Production Snippet
            required: false
            sortOrder: 3
          c4013d73-abb2-4daa-bab0-5b4bf9ffb018: # Development Snippet
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
handle: googleTagManager
name: 'Google Tag Manager'
sortOrder: 3
