enableVersioning: true
handle: ctas
name: 'Call To Actions'
propagationMethod: all
siteSettings:
  076725fd-bc7e-48fa-88ce-2d58cbee2749: # Arcadia Bluffs (en-US)
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
