enableVersioning: true
handle: footerMenu
name: 'Footer Menu'
propagationMethod: all
siteSettings:
  076725fd-bc7e-48fa-88ce-2d58cbee2749: # Arcadia Bluffs (en-US)
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 0b22c65f-9663-4532-b405-85ff71222fdf
type: structure
