enableVersioning: true
handle: giftCards
name: 'Gift Cards'
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  076725fd-bc7e-48fa-88ce-2d58cbee2749: # Arcadia Bluffs (en-US)
    enabledByDefault: true
    hasUrls: true
    template: _pages/gift-cards
    uriFormat: gift-cards
type: single
