enableVersioning: true
handle: mobileMenu
name: 'Mobile Menu'
propagationMethod: all
siteSettings:
  076725fd-bc7e-48fa-88ce-2d58cbee2749: # Arcadia Bluffs (en-US)
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 2ca10f12-ae8a-452a-bb41-b1518d8d49ce
type: structure
