enableVersioning: true
handle: primaryMenu
name: 'Primary Menu'
propagationMethod: all
siteSettings:
  076725fd-bc7e-48fa-88ce-2d58cbee2749: # Arcadia Bluffs (en-US)
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: a8299703-66d5-4c65-a7a5-6f95b2d95a08
type: structure
